#!/usr/bin/env bash

# paths needed for pyenv
PYENV_ROOT=$HOME/.pyenv
PATH=$PYENV_ROOT/bin:$PATH
C_INCLUDE_PATH=$PYENV_ROOT/include:$C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=$PYENV_ROOT/include:$CPLUS_INCLUDE_PATH
LIBRARY_PATH=$PYENV_ROOT/lib:$LIBRARY_PATH
LD_LIBRARY_PATH=$PYENV_ROOT/lib:$LD_LIBRARY_PATH
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
eval "$(pyenv init -)"
